# Generated by Django 6.0.1 on 2026-01-26 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_part_code', models.CharField(max_length=50, unique=True)),
                ('sub_part_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubPartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubPartStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('new_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_status_history', to='tracking.status')),
                ('old_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='old_status_history', to='tracking.status')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.product')),
                ('sub_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.subpart')),
            ],
        ),
        migrations.AddField(
            model_name='subpart',
            name='sub_part_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.subparttype'),
        ),
        migrations.CreateModel(
            name='ProductSubPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.product')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.status')),
                ('sub_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.subpart')),
            ],
            options={
                'unique_together': {('product', 'sub_part')},
            },
        ),
    ]
