# Generated by Django 6.0.1 on 2026-01-28 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpartstatushistory',
            name='product',
        ),
    ]
