# Generated by Django 6.0.1 on 2026-02-02 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_remove_subpartstatushistory_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subpart',
            name='default_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subpart',
            name='default_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_subpart_status', to='tracking.status'),
        ),
        migrations.AddField(
            model_name='subpart',
            name='default_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subpart',
            name='default_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_subpart_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
