# Generated by Django 6.0.1 on 2026-02-11 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_create_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMainType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='tracking.productmaintype')),
            ],
            options={
                'unique_together': {('main_type', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tracking.productrange'),
        ),
    ]
